name: Self-hosted runner (push)

on:
  push:
    branches:
      - master
      - ci_*
      - ci-*
      - improved-testing-experience
    paths:
      - "src/**"
      - "tests/**"
      - ".github/**"
      - "templates/**"
      - "utils/**"
  repository_dispatch:

env:
  HF_HOME: /mnt/cache
  TRANSFORMERS_IS_CI: yes
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  PYTEST_TIMEOUT: 60

jobs:
  list-test-folders:
    runs-on: [self-hosted, docker-gpu-test2, single-gpu]
    container:
      image: huggingface/pytorch-latest-release-gpu
      options: --gpus 0 --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Launcher docker
        uses: actions/checkout@v2

      - id: set-matrix
        working-directory: tests
        run: echo "::set-output name=matrix::$(python -c 'import os; print(list(filter(os.path.isdir, os.listdir(os.getcwd()))))')"

      - name: NVIDIA-SMI
        run: |
          nvidia-smi
          
      - name: Are GPUs recognized by our DL frameworks
        run: |
          utils/print_env_pt.py

  run_tests_torch_gpu:
    runs-on: [self-hosted, docker-gpu-test2, single-gpu]
    container:
      image: huggingface/pytorch-latest-release-gpu
      options: --gpus 0 --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    needs: list-test-folders
    strategy:
      matrix:
        folders: ${{ fromJson(needs.list-test-folders.outputs.matrix) }}
    steps:
      - name: Echo folder ${{ matrix.folders }}
        run: echo "${{ matrix.folders }}"

      - name: Run all non-slow tests on GPU
        run: python -m pytest --dist=loadfile -v --make-reports=tests_torch_gpu_${{ matrix.folders }} ${{ matrix.folders }} -k config

      - name: Failure short reports
        if: ${{ failure() }}
        run: cat reports/tests_torch_gpu_${{ matrix.folders }}_failures_short.txt

      - name: Test suite reports artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: run_all_tests_torch_gpu_${{ matrix.folders }}_test_reports
          path: reports